CREATE TYPE "UserRole" AS ENUM ('SUPERADMIN','ADMIN','MANAGER','DISPATCHER','TECHNICIAN');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE','DISABLED');
CREATE TYPE "DeviceStatus" AS ENUM ('PENDING','ACTIVE','DISABLED');
CREATE TABLE "Organization"("id" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Organization_pkey" PRIMARY KEY("id"));
CREATE TABLE "User"("id" TEXT NOT NULL,"organizationId" TEXT,"name" TEXT NOT NULL,"email" TEXT NOT NULL,"phone" TEXT,"passwordHash" TEXT NOT NULL,"role" "UserRole" NOT NULL DEFAULT 'ADMIN',"status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',"lastLogin" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY("id"));
CREATE TABLE "Technician"("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"employeeNumber" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT,"phone" TEXT,"status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Technician_pkey" PRIMARY KEY("id"));
CREATE TABLE "Device"("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"technicianId" TEXT,"deviceUuid" TEXT NOT NULL,"deviceName" TEXT NOT NULL,"manufacturer" TEXT,"model" TEXT,"androidVersion" TEXT,"appVersion" TEXT,"status" "DeviceStatus" NOT NULL DEFAULT 'PENDING',"batteryLevel" INTEGER,"lastLatitude" DOUBLE PRECISION,"lastLongitude" DOUBLE PRECISION,"lastSpeed" DOUBLE PRECISION,"lastAccuracy" DOUBLE PRECISION,"lastHeading" DOUBLE PRECISION,"lastSeen" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Device_pkey" PRIMARY KEY("id"));
CREATE TABLE "PairingCode"("id" TEXT NOT NULL,"deviceId" TEXT NOT NULL,"deviceIdText" TEXT NOT NULL,"codeHash" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"usedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PairingCode_pkey" PRIMARY KEY("id"));
CREATE TABLE "Location"("id" TEXT NOT NULL,"deviceId" TEXT NOT NULL,"technicianId" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"recordedAt" TIMESTAMP(3) NOT NULL,"latitude" DOUBLE PRECISION NOT NULL,"longitude" DOUBLE PRECISION NOT NULL,"speed" DOUBLE PRECISION,"heading" DOUBLE PRECISION,"accuracy" DOUBLE PRECISION,"altitude" DOUBLE PRECISION,"battery" INTEGER,"networkState" TEXT,"quality" TEXT NOT NULL DEFAULT 'GOOD',"syncedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Location_pkey" PRIMARY KEY("id"));
CREATE TABLE "Trip"("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"technicianId" TEXT NOT NULL,"deviceId" TEXT NOT NULL,"startedAt" TIMESTAMP(3) NOT NULL,"endedAt" TIMESTAMP(3),"startLatitude" DOUBLE PRECISION NOT NULL,"startLongitude" DOUBLE PRECISION NOT NULL,"endLatitude" DOUBLE PRECISION,"endLongitude" DOUBLE PRECISION,"distanceMeters" DOUBLE PRECISION NOT NULL DEFAULT 0,"drivingSeconds" INTEGER NOT NULL DEFAULT 0,"maxSpeed" DOUBLE PRECISION NOT NULL DEFAULT 0,"averageSpeed" DOUBLE PRECISION NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Trip_pkey" PRIMARY KEY("id"));
CREATE TABLE "Branding"("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"applicationName" TEXT NOT NULL,"companyName" TEXT NOT NULL,"logoUrl" TEXT,"faviconUrl" TEXT,"primaryColor" TEXT NOT NULL DEFAULT '#0ea5e9',"secondaryColor" TEXT NOT NULL DEFAULT '#0f172a',"loginBackgroundUrl" TEXT,"supportEmail" TEXT,"supportPhone" TEXT,"timezone" TEXT NOT NULL DEFAULT 'UTC',"country" TEXT,CONSTRAINT "Branding_pkey" PRIMARY KEY("id"));
CREATE TABLE "AuditLog"("id" TEXT NOT NULL,"userId" TEXT,"organizationId" TEXT,"action" TEXT NOT NULL,"resource" TEXT NOT NULL,"resourceId" TEXT,"ipAddress" TEXT,"result" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "Organization_slug_key" ON "Organization"("slug");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Technician_org_employee_key" ON "Technician"("organizationId","employeeNumber");
CREATE INDEX "Technician_org_status_idx" ON "Technician"("organizationId","status");
CREATE UNIQUE INDEX "Device_uuid_key" ON "Device"("deviceUuid");
CREATE INDEX "Device_org_status_idx" ON "Device"("organizationId","status");
CREATE INDEX "PairingCode_hash_expiry_idx" ON "PairingCode"("codeHash","expiresAt");
CREATE UNIQUE INDEX "Location_device_time_key" ON "Location"("deviceId","recordedAt");
CREATE INDEX "Location_org_time_idx" ON "Location"("organizationId","recordedAt");
CREATE INDEX "Location_tech_time_idx" ON "Location"("technicianId","recordedAt");
CREATE INDEX "Trip_org_start_idx" ON "Trip"("organizationId","startedAt");
CREATE UNIQUE INDEX "Branding_org_key" ON "Branding"("organizationId");
CREATE INDEX "Audit_org_time_idx" ON "AuditLog"("organizationId","createdAt");
ALTER TABLE "User" ADD CONSTRAINT "User_org_fk" FOREIGN KEY("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Technician" ADD CONSTRAINT "Technician_org_fk" FOREIGN KEY("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Device" ADD CONSTRAINT "Device_org_fk" FOREIGN KEY("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Device" ADD CONSTRAINT "Device_tech_fk" FOREIGN KEY("technicianId") REFERENCES "Technician"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PairingCode" ADD CONSTRAINT "PairingCode_device_fk" FOREIGN KEY("deviceId") REFERENCES "Device"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Location" ADD CONSTRAINT "Location_device_fk" FOREIGN KEY("deviceId") REFERENCES "Device"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Location" ADD CONSTRAINT "Location_tech_fk" FOREIGN KEY("technicianId") REFERENCES "Technician"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Location" ADD CONSTRAINT "Location_org_fk" FOREIGN KEY("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Trip" ADD CONSTRAINT "Trip_org_fk" FOREIGN KEY("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Trip" ADD CONSTRAINT "Trip_tech_fk" FOREIGN KEY("technicianId") REFERENCES "Technician"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Branding" ADD CONSTRAINT "Branding_org_fk" FOREIGN KEY("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "Audit_user_fk" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
